### ISSUE TITLE
Trial Dusk and Trial Night Crashes

### ISSUE THREAD

**Issue by kwadroke** [pixelmek-3d/pixelmek-3d#10]
"Trial Day" works fine.

When moving towards enemies on "Trial Dusk" and "Trial Night", the game crashes.
Using latest Git commits on Main (commit e4dd824). 
Attempted with Timber Wolf and Fire Moth. Probably other mechs will do the same.

Console Output:

``Initializing Camera
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x955840]

goroutine 40 [running]:
github.com/pixelmek-3d/pixelmek-3d/game.(*Game).updatePlayer(0xc000004f00)
        /home/kwadroke/code/pixelmek-3d/game/game.go:491 +0xb40
github.com/pixelmek-3d/pixelmek-3d/game.(*GameScene).Update(0xc002cc8270)
        /home/kwadroke/code/pixelmek-3d/game/scene_game.go:82 +0x111
github.com/pixelmek-3d/pixelmek-3d/game.(*Game).Update(0xc000004f00)
        /home/kwadroke/code/pixelmek-3d/game/game.go:302 +0x3b
github.com/hajimehoshi/ebiten/v2.(*gameForUI).Update(0xc000333e30)
        /home/kwadroke/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/gameforui.go:142 +0x23
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc00048b680, {0x24903f0?, 0xc000149200}, 0x1, 0x408e000000000000, 0x4088000000000000, 0x7fcefc743f18?, 0x29bae00, 0x0?, 0xc0006d7560)
        /home/kwadroke/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/ui/context.go:145 +0x3f2
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc00071d800?, {0x24903f0, 0xc000149200}, 0xc000097798?, 0xc000358000?, 0xc0000976e0?, 0xc000486eb0?, 0xc000486eb0?)
        /home/kwadroke/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/ui/context.go:75 +0x89
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateGame(0x29bae00)
        /home/kwadroke/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/ui/ui_glfw.go:1231 +0x1da
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loopGame(0x29bae00)
        /home/kwadroke/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/ui/ui_glfw.go:1199 +0xac
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func2()
        /home/kwadroke/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/ui/run_glfw_notsinglethread.go:60 +0x37
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/kwadroke/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /home/kwadroke/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
`

**Comment by harbdog** [comment]
@kwadroke thanks for the bug report! Can you also tell me what OS version and golang version was used?

**Comment by kwadroke** [comment]
OS: Fedora 38 x86_64

go version go1.21.8 linux/amd64

**Comment by kwadroke** [comment]
It was working fine until the last merge from the 17th

**Comment by harbdog** [comment]
I'm unable to reproduce on Linux Mint 21.3 x86_64, though since you're using Fedora one possible explanation is that you're using wayland. I'll ask around the ebitengine chat to see if the stack trace shown looks familiar to anyone.

**Comment by kwadroke** [comment]
I'm using Xorg with IceWM, so it's not a Wayland issue.

**Comment by harbdog** [comment]
> I'm using Xorg with IceWM, so it's not a Wayland issue.

Thanks for confirming that too, I think I see where it may be now too since you said it started with the 17th which was before I upgrade ebitengine to its most recent version.

**Comment by harbdog** [comment]
I was able to reproduce by heading for the nearest nav point, without first selecting a nav point using the `N` key. PR #11 fixes the issue.

Thanks again @kwadroke for bringing the issue forward!

**Comment by kwadroke** [comment]
You're right. I did cross the nav point without selecting it first. Was using it as a marker for testing.

**Comment by kwadroke** [comment]
I can confirm that it is fixed now.
