### ISSUE TITLE
Game Crashes during new PixelMek 3D splash screen transition

### ISSUE THREAD

**Issue by kwadroke** [pixelmek-3d/pixelmek-3d#23]
### PixelMek-3D Version

Commit 7a04721

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Web Browsers

### What steps will reproduce the problem?

Start the game as usual.

Might be my Potato of a machine, but prior to PR #22 the game ran fine.

### What is the expected result?

Successfully transition to game selection screen (Aka the screen with "Instant Action", "Settings", etc buttons).

### What happens instead?

After new animated PixelMek 3D splash with MadCat ("Press Any Key"), before the game selection screen is completely drawn, the game crashes.

I can see the top buttons, but before about 1/2 the screen is shown/drawn the game exits.

Error on console:

```
$ ./pixelmek-3d
radeon: Failed to allocate a buffer:
radeon:    size      : 1073741824 bytes
radeon:    alignment : 8192 bytes
radeon:    domains   : 4
radeon:    flags     : 20
radeon: Failed to allocate a buffer:
radeon:    size      : 1073741824 bytes
radeon:    alignment : 8192 bytes
radeon:    domains   : 4
radeon:    flags     : 20
radeon: Failed to allocate a buffer:
radeon:    size      : 1073741824 bytes
radeon:    alignment : 8192 bytes
radeon:    domains   : 4
radeon:    flags     : 20
radeon: Failed to allocate a buffer:
radeon:    size      : 1073741824 bytes
radeon:    alignment : 8192 bytes
radeon:    domains   : 4
radeon:    flags     : 20
2024-06-08 09:13:22 [FATAL] opengl: creating framebuffer failed: 36061
```

### Anything else you feel useful to add?

System Specs:

```
System:
  Host: elkfed Kernel: 6.8.11-200.fc39.x86_64 arch: x86_64 bits: 64
  Desktop: dwm v: N/A Distro: Fedora Linux 39 (Server Edition)
CPU:
  Info: dual core Intel Core i3-2130 [MT MCP] speed (MHz): avg: 1684
    min/max: 1600/3400
Graphics:
  Device-1: AMD Cedar [Radeon HD 5000/6000/7350/8350 Series] driver: radeon
    v: kernel
  Display: x11 server: X.Org v: 1.20.14 driver: X: loaded: modesetting
    dri: r600 gpu: radeon resolution: 1: 2112x1188~60Hz 2: 1408x1127~60Hz
  API: OpenGL v: 4.5 vendor: mesa v: 23.3.6 renderer: AMD CEDAR (DRM 2.50.0
    / 6.8.11-200.fc39.x86_64 LLVM 17.0.6)
Info:
  Memory: total: 8 GiB available: 7.7 GiB used: 3.05 GiB (39.5%)
  Processes: 239 Uptime: 10m Shell: Bash inxi: 3.3.34

```
``

Go
```
$ go version
go version go1.21.10 linux/amd64
```

**Comment by kwadroke** [comment]
Screen just before the crash:

![Screenshot_2024-06-08_09-51-33](https://github.com/pixelmek-3d/pixelmek-3d/assets/3247032/9169152f-c0dc-4142-9304-ed1d6916c76d)

Somehow I did get it to make it to the selection screen once while trying to take a screenshot while the window was not active.

**Comment by harbdog** [comment]
Thanks for the bug report! I have an old linux potato laptop that I can try to reproduce on.

**Comment by harbdog** [comment]
On my old potatotop I got past the intro, but it crashes hard when trying to load in-mission with graphics glitches and then the following message repeats dozens of times:

`radeon: Not enough memory for command submission.`

Here's the stats on that machine for comparison:

```
2010 Dell Studio 1558
Linux Mint 21.1 (kernel 5.15.0-92-generic)
Intel i3 M330
4GB RAM
Radeon Mobility HD 4530
```

**Comment by harbdog** [comment]
After applying updates, since it's been a while, I tried again just in case. This time I noticed the message about not enough memory happens as soon as the intro scene, and I noticed a small texture glitch during the intro transition. It doesn't panic/crash however, just unplayable due to texture glitches. I think it's pretty fair to say there's just not enough video memory there.

![Screenshot at 2024-06-08 21-45-48](https://github.com/pixelmek-3d/pixelmek-3d/assets/1300522/edef7d60-079d-4d22-b0d5-f29fbba1a1ee)

![Screenshot at 2024-06-08 21-20-05](https://github.com/pixelmek-3d/pixelmek-3d/assets/1300522/6b311eae-bf76-4a82-8356-c2a78fca470d)

**Comment by harbdog** [comment]
Since I can't directly reproduce, maybe I can just add a config option to disable shaders entirely, that way if that's the only thing causing issues for you then you'd still be able to play at least.

**Comment by harbdog** [comment]
@kwadroke can you checkout the branch from PR #25 and run the game with the new `--disable-shaders` command line argument?

**Comment by harbdog** [comment]
Interestingly, the game runs well on a 2015 Macbook Air with 8GB RAM and Intel HD 6000 GPU.

**Comment by harbdog** [comment]
@kwadroke alternatively I have discovered that I'm having performance issues even on non-potato hardware during the splash/intro transition segments, and I think the use of stagehand may be why. To try this out I've put together PR #26 to recreate the intro and shader transitions used without involving stagehand, instead using my previous slightly kludgy but more performant way of handling scene transitions.

**Comment by harbdog** [comment]
I just tried that back out on my potatotop and found it works just fine, so the problem isn't the excessive shader user, rather that stagehand introduces some amount of performance overhead. So I'll plan to back that out soon.

**Comment by harbdog** [comment]
I think the root cause is that stagehand has two scenes updating and drawing at the same time during transitions, and because I was using the director to manage all transitions and scenes up front likely meant that there was no garbage cleanup happening.

**Comment by kwadroke** [comment]
Can confirm new commits work on my Potato PC.
