### ISSUE TITLE
Idle/Non-moving Mechs play animation when they should not.

### ISSUE THREAD

**Issue by kwadroke** [pixelmek-3d/pixelmek-3d#24]
### PixelMek-3D Version

Any

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Web Browsers

### What steps will reproduce the problem?

Play the game, any scenario.

### What is the expected result?

Mechs that are not moving should not be animated like they are walking.

### What happens instead?

Idle/non moving mechs appear to be moving even though they do not change locations.

### Anything else you feel useful to add?

Very Minor/cosmetic issue that has existed almost the entirety of the project but just now reporting it.

**Comment by harbdog** [comment]
The idle animation is intended to only move the torso and arms like it's "breathing", so as long as the legs aren't moving that's intended.

**Comment by kwadroke** [comment]
Never saw a mech "breathing" before :)
Just looks a little odd being they're standing still.

**Comment by harbdog** [comment]
It's a style I borrowed from old JRPG like Front Mission:

https://youtu.be/XieNGBnkaFo?si=csa5epB7MhrQwAro&t=1593
